name: config
variables:
  - name: url
    value: https://fesp-api.koyeb.app/market
  - name: client-id
    value: febc15-final12-ecad
  - name: accessToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjIsInR5cGUiOiJzZWxsZXIiLCJpYXQiOjE3NzI3ODE1ODEsImV4cCI6MTc3Mjg2Nzk4MSwiaXNzIjoiRkVCQyJ9.7vIEISQfyPmvuMzJYrt-URevPxtRooDXkLFkiz9N5Og
  - name: refreshToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NzI3ODE1ODIsImV4cCI6MTc3NTM3MzU4MiwiaXNzIjoiRkVCQyJ9.HpcSwGTdDrwa29HNBnRNZpyzYFPc57HapQxjfA5ccwI
