import type { Product, Study, ChatMessage } from './types';

/** 상품 목록 mock: price, quantity, name, content 필수 / shippingFees, mainImages, show, extra 선택 */
export const initialProducts: Product[] = [
  {
    id: '1',
    name: 'React + Next.js 심화 스터디',
    content:
      '프론트엔드 개발자를 위한 React와 Next.js 심화 학습 스터디입니다. 매주 토요일 오후 2시에 모여서 공식 문서를 함께 읽고, 실습 프로젝트를 진행합니다. 기초 지식이 있으신 분들 환영합니다!',
    price: 0,
    quantity: 6,
    shippingFees: 0,
    show: true,
    extra: { category: '개발', tags: ['React', 'Next.js', 'TypeScript'] },
  },
  {
    id: '2',
    name: '알고리즘 문제풀이 스터디',
    content:
      '코딩테스트 대비를 위한 알고리즘 스터디입니다. 백준, 프로그래머스 문제를 함께 풀고 풀이를 공유합니다. 주 3회 온라인으로 진행하며, 매일 1문제씩 풀어옵니다.',
    price: 0,
    quantity: 8,
    shippingFees: 0,
    show: true,
    extra: { category: '개발', tags: ['알고리즘', 'Python', '코딩테스트'] },
  },
  {
    id: '3',
    name: 'UI/UX 디자인 포트폴리오 스터디',
    content:
      'Figma를 활용한 UI/UX 디자인 포트폴리오 제작 스터디입니다. 매주 각자의 작업물을 공유하고 피드백을 주고받습니다. 취업 준비 중이신 분들 환영!',
    price: 0,
    quantity: 5,
    shippingFees: 0,
    show: false,
    extra: { category: '디자인', tags: ['Figma', 'UI/UX'] },
  },
  {
    id: '4',
    name: 'AWS 자격증 준비 스터디',
    content:
      'AWS Solutions Architect Associate 자격증 취득을 목표로 하는 스터디입니다. 공식 학습 자료와 모의고사를 함께 풀며 준비합니다.',
    price: 0,
    quantity: 4,
    shippingFees: 0,
    mainImages: ['/images/aws-study.jpg'],
    show: true,
    extra: { category: '자격증', tags: ['AWS', 'Cloud'] },
  },
  {
    id: '5',
    name: '영어 회화 스터디',
    content:
      '비즈니스 영어 회화 실력 향상을 위한 스터디입니다. 매주 다양한 주제로 토론하며 스피킹 실력을 키웁니다. 중급 이상 레벨 추천드립니다.',
    price: 0,
    quantity: 6,
    show: true,
    extra: { category: '어학', tags: ['영어', '비즈니스영어'] },
  },
];

export const initialStudies: Study[] = [
  {
    id: '1',
    title: 'React + Next.js 심화 스터디',
    description:
      '프론트엔드 개발자를 위한 React와 Next.js 심화 학습 스터디입니다. 매주 토요일 오후 2시에 모여서 공식 문서를 함께 읽고, 실습 프로젝트를 진행합니다. 기초 지식이 있으신 분들 환영합니다!',
    category: '개발',
    tags: ['React', 'Next.js', 'TypeScript'],
    maxMembers: 6,
    currentMembers: 3,
    hostId: 'user-2',
    hostName: '이프론트',
    location: {
      name: '강남역 스터디카페',
      lat: 37.4979,
      lng: 127.0276,
    },
    schedule: '매주 토요일 14:00 - 17:00',
    startDate: '2026-03-15',
    endDate: '2026-06-15',
    isClosed: false,
    createdAt: '2026-03-01T09:00:00Z',
    participants: [
      {
        id: 'p-1',
        studyId: 'study-1',
        userId: 'user-3',
        userName: '박백엔드',
        status: 'approved',
        message: '프론트엔드도 배우고 싶어서 신청합니다!',
        appliedAt: '2026-03-02T10:00:00Z',
      },
      {
        id: 'p-2',
        studyId: 'study-1',
        userId: 'user-4',
        userName: '최주니어',
        status: 'approved',
        message: 'React 기초는 알고 있습니다. 심화 학습하고 싶어요.',
        appliedAt: '2026-03-03T14:30:00Z',
      },
      {
        id: 'p-3',
        studyId: 'study-1',
        userId: 'user-5',
        userName: '정신입',
        status: 'pending',
        message: '열심히 하겠습니다!',
        appliedAt: '2026-03-05T08:00:00Z',
      },
    ],
  },
  {
    id: '2',
    title: '알고리즘 문제풀이 스터디',
    description:
      '코딩테스트 대비를 위한 알고리즘 스터디입니다. 백준, 프로그래머스 문제를 함께 풀고 풀이를 공유합니다. 주 3회 온라인으로 진행하며, 매일 1문제씩 풀어옵니다.',
    category: '개발',
    tags: ['알고리즘', 'Python', '코딩테스트'],
    maxMembers: 8,
    currentMembers: 5,
    hostId: 'user-6',
    hostName: '김알고',
    location: {
      name: '판교 카페',
      lat: 37.395,
      lng: 127.1116,
    },
    schedule: '월/수/금 20:00 - 22:00 (온라인)',
    startDate: '2026-03-10',
    isClosed: false,
    createdAt: '2026-03-05T15:00:00Z',
    participants: [
      {
        id: 'p-4',
        studyId: 'study-2',
        userId: 'user-7',
        userName: '이코테',
        status: 'approved',
        message: '취준 중입니다. 같이 열심히 해요!',
        appliedAt: '2026-03-06T09:00:00Z',
      },
    ],
  },
  {
    id: '3',
    title: 'UI/UX 디자인 포트폴리오 스터디',
    description:
      'Figma를 활용한 UI/UX 디자인 포트폴리오 제작 스터디입니다. 매주 각자의 작업물을 공유하고 피드백을 주고받습니다. 취업 준비 중이신 분들 환영!',
    category: '디자인',
    tags: ['Figma', 'UI/UX'],
    maxMembers: 5,
    currentMembers: 5,
    hostId: 'user-8',
    hostName: '박디자인',
    location: {
      name: '홍대 작업실',
      lat: 37.5563,
      lng: 126.9239,
    },
    schedule: '매주 일요일 13:00 - 16:00',
    startDate: '2026-02-20',
    endDate: '2026-05-20',
    isClosed: true,
    createdAt: '2026-02-15T11:00:00Z',
    participants: [],
  },
  {
    id: '4',
    title: 'AWS 자격증 준비 스터디',
    description:
      'AWS Solutions Architect Associate 자격증 취득을 목표로 하는 스터디입니다. 공식 학습 자료와 모의고사를 함께 풀며 준비합니다.',
    category: '자격증',
    tags: ['AWS', 'Cloud'],
    maxMembers: 4,
    currentMembers: 2,
    hostId: 'user-9',
    hostName: '최클라우드',
    location: {
      name: '역삼역 스터디룸',
      lat: 37.5006,
      lng: 127.0366,
    },
    schedule: '매주 화/목 19:00 - 21:00',
    startDate: '2026-03-20',
    endDate: '2026-05-20',
    isClosed: false,
    createdAt: '2026-03-10T10:00:00Z',
    participants: [
      {
        id: 'p-5',
        studyId: 'study-4',
        userId: 'user-10',
        userName: '강서버',
        status: 'pending',
        message: 'AWS 자격증 같이 준비하고 싶습니다.',
        appliedAt: '2026-03-11T16:00:00Z',
      },
    ],
  },
  {
    id: '5',
    title: '영어 회화 스터디',
    description:
      '비즈니스 영어 회화 실력 향상을 위한 스터디입니다. 매주 다양한 주제로 토론하며 스피킹 실력을 키웁니다. 중급 이상 레벨 추천드립니다.',
    category: '어학',
    tags: ['영어', '비즈니스영어'],
    maxMembers: 6,
    currentMembers: 4,
    hostId: 'user-11',
    hostName: '김영어',
    location: {
      name: '선릉역 카페',
      lat: 37.5045,
      lng: 127.0498,
    },
    schedule: '매주 수요일 19:30 - 21:30',
    startDate: '2026-03-01',
    isClosed: false,
    createdAt: '2026-02-25T14:00:00Z',
    participants: [],
  },
];

export const initialMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    studyId: 'study-1',
    userId: 'user-2',
    userName: '이프론트',
    content:
      '안녕하세요! 첫 모임은 3월 15일 토요일입니다. 강남역 3번 출구 앞에서 만나요!',
    createdAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'msg-2',
    studyId: 'study-1',
    userId: 'user-3',
    userName: '박백엔드',
    content: '네! 알겠습니다. 혹시 노트북 필수인가요?',
    createdAt: '2026-03-10T10:05:00Z',
  },
  {
    id: 'msg-3',
    studyId: 'study-1',
    userId: 'user-2',
    userName: '이프론트',
    content: '네, 노트북 꼭 가져오세요. 실습 위주로 진행합니다.',
    createdAt: '2026-03-10T10:10:00Z',
  },
  {
    id: 'msg-4',
    studyId: 'study-1',
    userId: 'user-4',
    userName: '최주니어',
    content: '저도 참여합니다! 기대되네요.',
    createdAt: '2026-03-10T11:00:00Z',
  },
];
